# Generated by Django 3.0.5 on 2020-04-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.GlobalSerial'),
        ),
    ]
