# Generated by Django 3.0.5 on 2020-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='Status',
            field=models.CharField(choices=[('0', 'Paid'), ('1', 'Free'), ('2', 'Unknown')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Title',
            field=models.CharField(default='S', max_length=256, unique=True),
        ),
    ]
