# Generated by Django 3.0.5 on 2020-04-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200418_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Description',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
